import type { Metadata } from "next"
import Link from "next/link"

import { Container, Mono, PageHeader, Panel, Prose } from "@/app/_shared/ui"
import { RampBrowser } from "./ramp-browser"
import { routes } from "@/lib/routes"
import { pageMetadata } from "@/app/_shared/seo"
import {
  JsonLd,
  breadcrumbLd,
  graph,
} from "@/app/_shared/structured-data"

export const metadata: Metadata = pageMetadata({
  title: "Colours",
  description:
    "Every colour token in opsinjs, read live from the stylesheet: four status levels, six measurement categories, and the neutral roles.",
  path: routes.colors(),
  type: "website",
  section: "Foundations",
})

/**
 * `/colors` is the colour browser.
 *
 * Two things separate this from the token table in the documentation. It reads
 * the LIVE stylesheet rather than the generated JSON, so it reports what your
 * device actually resolves including the Display-P3 escalation; and it is a
 * copy surface rather than a reference. You come here to take a value away with
 * you, not to read about one.
 *
 * The measured numbers deliberately live elsewhere. Contrast is generated by
 * `check-contrast.mts` and published in the reference, because a figure typed
 * onto a marketing page is a figure nobody regression-tests.
 */
export default function ColorsPage() {
  return (
    <>
      {/*
        The trail Google prints in place of a truncated URL. The site
        entity and the publisher are declared once on the root layout and
        referred to by `@id`, so this block carries only what is local to
        this page.
      */}
      <JsonLd
        data={graph([
          breadcrumbLd([
            { name: "Introduction", path: routes.home() },
            { name: "Colours", path: routes.colors() },
          ]),
        ])}
      />
      <PageHeader
        eyebrow="Tokens"
        title="Colour"
        lead="Two axes that never meet on one element, read live from the stylesheet your browser is running."
      />

      <Container className="py-10">
        <div className="grid gap-8 lg:grid-cols-[2fr_1fr]">
          <Prose>
            <p>
              <strong>Category</strong> says what kind of measurement this is: a
              heart rate, a blood sugar, a night&rsquo;s sleep. It is low-chroma
              and it never means anything is wrong. <strong>Status</strong> says
              how urgent this is, on four levels, and it is high-chroma because
              somebody has to act on it. An element takes its colour from one of
              them, never both.
            </p>
            <p>
              Every swatch below is a CSS custom property read from your
              browser, so it is the value in effect on this screen. Dark mode,
              Display-P3 and your accessibility settings are already applied.
            </p>
          </Prose>

          <Panel className="h-fit">
            <h2 className="text-sm font-semibold tracking-wide uppercase">
              Where the numbers are
            </h2>
            <ul className="mt-3 space-y-3 text-sm leading-relaxed text-muted-foreground">
              <li>
                <Link
                  className="text-foreground underline underline-offset-4"
                  href={routes.docs("foundations", "colour")}
                >
                  Contrast and APCA
                </Link>{" "}
                explains which measure is the floor here.
              </li>
              <li>
                <Link
                  className="text-foreground underline underline-offset-4"
                  href={routes.docs("reference", "generated", "contrast")}
                >
                  Measured contrast
                </Link>{" "}
                covers every token pair in both themes, generated and dated.
              </li>
              <li>
                <Link
                  className="text-foreground underline underline-offset-4"
                  href={routes.playgroundContrast()}
                >
                  Contrast oracle
                </Link>{" "}
                checks any pair of your own.
              </li>
              <li>
                <Link
                  className="text-foreground underline underline-offset-4"
                  href={routes.playgroundTheme()}
                >
                  Theme generator
                </Link>{" "}
                runs a brand colour through the ramp and shows where it fails.
              </li>
            </ul>
          </Panel>
        </div>

        <hr className="my-10 border-border" />

        <RampBrowser />

        <section className="mt-14">
          <h2 className="text-lg font-semibold tracking-tight">
            Using these values
          </h2>
          <Prose className="mt-3">
            <p>
              Copy the <Mono>var()</Mono> form wherever you can. It follows the
              theme, the gamut and the accessibility media queries. A hex value
              pasted into a component follows none of them, and that is the
              usual way a themed system stops being themed.
            </p>
            <p>
              Every token here also has a Tailwind utility, such as{" "}
              <Mono>bg-status-urgent-surface</Mono>.{" "}
              <Link href={`${routes.docs("theming")}#tailwind-v4-and-css-variables`}>
                Tailwind v4 and CSS variables
              </Link>{" "}
              explains how they are wired.
            </p>
          </Prose>
        </section>
      </Container>
    </>
  )
}
