import type { Metadata } from "next"
import Link from "next/link"

import { Container, Mono, PageHeader, Panel, Prose } from "@/app/_shared/ui"
import { RampBrowser } from "./ramp-browser"
import { routes } from "@/lib/routes"

export const metadata: Metadata = {
  title: "Colours",
  description:
    "Every colour token in opsinjs, read live from the running stylesheet: the four clinical status levels, the six measurement categories, and the neutral roles this documentation site is drawn with.",
}

/**
 * `/colors` is the colour browser.
 *
 * Two things separate this from the token table in the documentation. It reads
 * the LIVE stylesheet rather than the generated JSON, so it reports what your
 * device actually resolves including the Display-P3 escalation; and it is a
 * copy surface rather than a reference. You come here to take a value away with
 * you, not to read about one.
 *
 * The measured numbers deliberately live elsewhere. Contrast is generated by
 * `check-contrast.mts` and published in the reference, because a figure typed
 * onto a marketing page is a figure nobody regression-tests.
 */
export default function ColorsPage() {
  return (
    <>
      <PageHeader
        eyebrow="Tokens"
        title="Colour"
        lead="Two axes that never meet on one element, read live from the stylesheet your browser is running."
      />

      <Container className="py-10">
        <div className="grid gap-8 lg:grid-cols-[2fr_1fr]">
          <Prose>
            <p>
              Health data has two independent colour dimensions and most systems
              have one. <strong>Category</strong> says what kind of measurement
              this is, such as a heart rate, a blood sugar or a night&rsquo;s
              sleep. It is identity, it is deliberately low-chroma, and it
              carries no verdict whatsoever. <strong>Status</strong> says how
              urgent this is, on four ordinal levels, and it is always
              high-chroma because it is a verdict somebody has to act on.
            </p>
            <p>
              An element takes its colour from exactly one of them. That is the
              rule the whole system is built around, and it is not a stylistic
              preference: a tile that is simultaneously &ldquo;cardio&rdquo; and
              &ldquo;urgent&rdquo; in two competing reds is a tile whose reader
              cannot tell which red means <em>phone somebody</em>.
            </p>
            <p>
              Nothing on this page is written down in a page. Every swatch is a
              CSS custom property resolved by your browser, so what you are
              reading is the value in effect on this display. The Display-P3
              escalation, dark mode and your operating system&rsquo;s
              accessibility preferences have already been applied.
            </p>
          </Prose>

          <Panel className="h-fit">
            <h2 className="text-sm font-semibold tracking-wide uppercase">
              Where the numbers are
            </h2>
            <ul className="mt-3 space-y-3 text-sm leading-relaxed text-muted-foreground">
              <li>
                <Link
                  className="text-foreground underline underline-offset-4"
                  href={routes.docs(
                    "foundations",
                    "colour",
                    "contrast-and-apca"
                  )}
                >
                  Contrast and APCA
                </Link>{" "}
                explains why both APCA Lc and WCAG 2.2 are published side by
                side, and which one this system treats as the floor.
              </li>
              <li>
                <Link
                  className="text-foreground underline underline-offset-4"
                  href={routes.docs("accessibility", "contrast-conformance")}
                >
                  Measured conformance
                </Link>{" "}
                covers every token pair, both themes, generated and dated. No
                figure on this site is typed by a human.
              </li>
              <li>
                <Link
                  className="text-foreground underline underline-offset-4"
                  href={routes.playgroundContrast()}
                >
                  Contrast oracle
                </Link>{" "}
                checks any pair of your own against the same implementation CI
                uses.
              </li>
              <li>
                <Link
                  className="text-foreground underline underline-offset-4"
                  href={routes.playgroundTheme()}
                >
                  Theme generator
                </Link>{" "}
                takes a brand colour through the ramp and shows where it fails.
              </li>
            </ul>
          </Panel>
        </div>

        <hr className="my-10 border-border" />

        <RampBrowser />

        <section className="mt-14">
          <h2 className="text-lg font-semibold tracking-tight">
            Using these values in your own code
          </h2>
          <Prose className="mt-3">
            <p>
              Copy the <Mono>var()</Mono> form wherever you can. A custom
              property follows the theme, the gamut escalation and every
              accessibility media query for free; a hex value pinned into a
              component follows none of them, and it is the single most common
              way a themed system stops being themed.
            </p>
            <p>
              The authored form is currently an <Mono>oklch()</Mono> triple.
              That form is what you want when you are generating a stylesheet,
              exporting to a design tool, or explaining to somebody why the ramp
              is perceptually even. The hex form is an sRGB clamp: correct on an
              sRGB display, lossy on a wide-gamut one, and never the definition.
            </p>
            <p>
              Tailwind utilities exist for every token on this page.{" "}
              <Mono>bg-status-urgent-surface</Mono> and{" "}
              <Mono>text-category-heart</Mono> are two of them. The utilities
              are declared with <Mono>@theme inline</Mono> so they resolve the
              custom property at use time rather than baking a value.{" "}
              <Link href={routes.docs("theming", "tailwind-v4")}>
                Tailwind v4 and the order that silently breaks
              </Link>{" "}
              explains why that distinction matters.
            </p>
          </Prose>
        </section>
      </Container>
    </>
  )
}
