import { getEntry } from "@/lib/catalogue"
import { getRegistryEntry } from "@/lib/registry"
import { DEFAULT_BASE, DEFAULT_STYLE } from "@/lib/routes"
import type { Status } from "@/lib/status"
import {
  ComponentPreview as ComponentPreviewSurface,
  IframePreview as IframePreviewSurface,
  type ComponentPreviewProps,
  type IframePreviewProps,
} from "./preview"

/* ==========================================================================
   preview-server.tsx — the registry lookup that <ComponentPreview> and
   <IframePreview> cannot do for themselves.

   THIS FILE EXISTS FOR EXACTLY ONE REASON: A BOOLEAN IS SMALL AND THE REGISTRY
   INDEX IS NOT.

   `preview.tsx` is `"use client"`, and it has to be: the theme, density, text
   and status switches are the mechanism behind a promise two pages make about
   a 200% Dynamic Type demonstration, and a switch that does not switch is
   worse than no switch. But `registry/__index__.ts` carries `source` — the
   FULL TEXT of every built component file — on every entry, and importing
   `@/lib/registry` from a client module would ship all of it to the browser on
   every one of the ~380 documentation pages, whether or not that page has a
   preview on it.

   So the lookup happens here, in a server component, and the only things that
   cross the boundary are `built: boolean` and `phase`, one release-phase word
   off the catalogue row. The client surface keeps every bit of its
   interactivity and gains nothing it has to download. Anything else a lookup
   turns up belongs on this side of the line.

   These two exports carry the public names. `components/mdx.tsx` registers
   `ComponentPreview` and `IframePreview` FROM THIS FILE; the same names in
   `./preview` are the client surfaces underneath and are not what MDX resolves
   to. If you ever import one of them directly, you get a preview that can
   never resolve a component, because nothing will have told it that one
   exists.
   ========================================================================== */

/**
 * True when this name really does render something at `/view`.
 *
 * `component !== null` rather than `entry !== null` is the whole check.
 * `getRegistryEntry` can return an entry whose `component` is null — the type
 * admits it — and framing a route for one of those would put an iframe around
 * the `/view` route's own not-built state, which teaches a reader that
 * previews are broken rather than that a component is unwritten.
 */
function resolvesToARender(
  name: string | undefined,
  base: string,
  style: string,
  kind: "component" | "example" | "screen"
): boolean {
  if (!name) return false
  const entry = getRegistryEntry(name, base, style, kind)
  return entry?.component != null
}

/**
 * The catalogue row's release phase, for the empty state's machine sentence.
 *
 * Resolved here for the same reason `built` is: the phase is a fact about
 * registry/catalogue.ts, and `lib/catalogue` must not cross into a client
 * module. Only the resolved word crosses, and it matters because <NotBuiltYet>
 * says something different at `considered` — where there is no specification —
 * from what it says at `planned`, where there is one. An id that is not a
 * catalogue row (an example, a screen) resolves to nothing and the surface
 * falls back to its own default.
 */
function phaseOf(name: string | undefined): Status | undefined {
  return name ? getEntry(name)?.status : undefined
}

/**
 * `built` is resolved here and never accepted from a caller. An MDX page that
 * could assert a component exists would be able to do the one thing this whole
 * site is built to prevent. `phase` is resolved on the same terms.
 */
export type ComponentPreviewServerProps = Omit<
  ComponentPreviewProps,
  "built" | "phase"
>

/** The preview block on a component page. See `./preview` for the surface. */
export function ComponentPreview(props: ComponentPreviewServerProps) {
  const {
    name,
    base = DEFAULT_BASE,
    style = DEFAULT_STYLE,
    kind = "component",
  } = props

  /*
   * The lookup uses the base and style the PAGE names, not the ones a reader
   * may have put in `?base=&style=`. A server component cannot see the query
   * string without opting the entire documentation corpus out of static
   * generation (AGENTS.md §3), and the query override is a reader's
   * deliberate act: if they point a preview at a base that has nothing in it,
   * the framed `/view` route answers for itself with its own
   * `data-opsin-view-state="not-built"`, under the product theme, generated by
   * the route that owns that fact rather than guessed at here.
   */
  const built = resolvesToARender(name, base, style, kind)

  return (
    <ComponentPreviewSurface {...props} built={built} phase={phaseOf(name)} />
  )
}

/** See `ComponentPreviewServerProps` — `built` is resolved, never passed. */
export type IframePreviewServerProps = Omit<IframePreviewProps, "built">

/** A `/view` route framed at a device width. See `./preview` for the surface. */
export function IframePreview(props: IframePreviewServerProps) {
  const {
    name,
    base = DEFAULT_BASE,
    style = DEFAULT_STYLE,
    kind = "component",
  } = props

  return (
    <IframePreviewSurface
      {...props}
      built={resolvesToARender(name, base, style, kind)}
    />
  )
}
